export type Direction = "up" | "stable" | "down";

export type MatrixCase = {
  id: number;
  group: "p_up" | "p_stable" | "p_down";
  groupLabel: string;
  deltaP: Direction;
  deltaD: Direction;
  deltaR: Direction;
  labelP: string;
  labelD: string;
  labelR: string;
  assessment: string;
  variant: "destructive" | "success" | "default" | "warning";
  explanation: string;
  action: string;
};

export const MATRIX_27_CASES: MatrixCase[] = [
  // Nhóm I: deltaP Tăng (Câu hỏi trở nên dễ hơn)
  {
    id: 1,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "up",
    deltaR: "up",
    labelP: "↑ Tăng",
    labelD: "↑ Tăng",
    labelR: "↑ Tăng",
    assessment: "Suy giảm độ khó (Trực quan: Tốt)",
    variant: "destructive",
    explanation: "Câu hỏi diễn đạt rõ ràng hơn, sinh viên hiểu đúng bài, phân hóa tốt nhưng câu hỏi đã bị dễ hơn ban đầu.",
    action: "Chấp nhận dùng nếu đây là câu hỏi thông hiểu; nếu là câu nâng cao thì cần tăng độ khó.",
  },
  {
    id: 2,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "up",
    deltaR: "stable",
    labelP: "↑ Tăng",
    labelD: "↑ Tăng",
    labelR: "→ Ổn",
    assessment: "Suy giảm độ khó",
    variant: "destructive",
    explanation: "Câu hỏi rõ ràng hơn, phân loại sinh viên khá giỏi tốt, độ ổn định đo lường giữ vững.",
    action: "Phù hợp làm câu hỏi kiểm tra chuẩn đầu ra mức độ trung bình.",
  },
  {
    id: 3,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "up",
    deltaR: "down",
    labelP: "↑ Tăng",
    labelD: "↑ Tăng",
    labelR: "↓ Giảm",
    assessment: "Suy giảm độ khó",
    variant: "destructive",
    explanation: "Phân loại được nhưng độ biến thiên câu trả lời cao, phương án nhiễu hoạt động chưa đều.",
    action: "Rà soát lại các phương án gây nhiễu để đảm bảo độ tin cậy.",
  },
  {
    id: 4,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "stable",
    deltaR: "up",
    labelP: "↑ Tăng",
    labelD: "→ Ổn",
    labelR: "↑ Tăng",
    assessment: "Suy giảm độ khó",
    variant: "destructive",
    explanation: "Câu hỏi dễ hơn nhưng vẫn giữ nguyên khả năng phân loại, đo lường ngày càng chuẩn xác.",
    action: "Phù hợp làm câu hỏi củng cố kiến thức nền tảng.",
  },
  {
    id: 5,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "stable",
    deltaR: "stable",
    labelP: "↑ Tăng",
    labelD: "→ Ổn",
    labelR: "→ Ổn",
    assessment: "Suy giảm độ khó",
    variant: "destructive",
    explanation: "Câu hỏi bị trôi về mức dễ hơn mà không thay đổi bất kỳ đặc tính phân loại nào khác.",
    action: "Cần xem lại đáp án có bị quá hiển nhiên hoặc sinh viên học thuộc lòng.",
  },
  {
    id: 6,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "stable",
    deltaR: "down",
    labelP: "↑ Tăng",
    labelD: "→ Ổn",
    labelR: "↓ Giảm",
    assessment: "Suy giảm độ khó",
    variant: "destructive",
    explanation: "Dễ hơn và độ tin cậy đo lường bắt đầu giảm (sinh viên có thể đánh lụi trúng).",
    action: "Kiểm tra tính chặt chẽ của các phương án sai.",
  },
  {
    id: 7,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "down",
    deltaR: "up",
    labelP: "↑ Tăng",
    labelD: "↓ Giảm",
    labelR: "↑ Tăng",
    assessment: "Suy giảm phân loại",
    variant: "destructive",
    explanation: "Câu hỏi quá dễ khiến hầu hết sinh viên đều làm đúng dẫn tới mất khả năng phân loại sinh viên.",
    action: "Cần bổ sung các bẫy logic hoặc tăng độ sâu câu hỏi.",
  },
  {
    id: 8,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "down",
    deltaR: "stable",
    labelP: "↑ Tăng",
    labelD: "↓ Giảm",
    labelR: "→ Ổn",
    assessment: "Suy giảm phân loại",
    variant: "destructive",
    explanation: "Câu hỏi bị đơn giản hóa quá mức, sinh viên yếu cũng dễ dàng vượt qua câu này.",
    action: "Tăng thêm các phương án nhiễu có tính thuyết phục hơn.",
  },
  {
    id: 9,
    group: "p_up",
    groupLabel: "Nhóm I: Tỷ lệ làm đúng tăng (Câu hỏi trở nên dễ hơn)",
    deltaP: "up",
    deltaD: "down",
    deltaR: "down",
    labelP: "↑ Tăng",
    labelD: "↓ Giảm",
    labelR: "↓ Giảm",
    assessment: "Suy giảm nghiêm trọng",
    variant: "destructive",
    explanation: "Câu hỏi bị quá dễ, mất hoàn toàn khả năng phân loại và độ tin cậy đo lường rất thấp.",
    action: "Biên tập lại toàn diện hoặc loại bỏ khỏi ngân hàng đề thi.",
  },

  // Nhóm II: deltaP Ổn định
  {
    id: 10,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "up",
    deltaR: "up",
    labelP: "→ Ổn",
    labelD: "↑ Tăng",
    labelR: "↑ Tăng",
    assessment: "Cải thiện tối ưu",
    variant: "success",
    explanation: "Trạng thái lý tưởng nhất: Giữ nguyên độ khó nhưng phân loại học sinh giỏi/kém sắc bén hơn.",
    action: "Mẫu câu hỏi chuẩn mực, ưu tiên tái sử dụng cho các kỳ thi sau.",
  },
  {
    id: 11,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "up",
    deltaR: "stable",
    labelP: "→ Ổn",
    labelD: "↑ Tăng",
    labelR: "→ Ổn",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Khả năng phân loại tăng lên, giữ vững tính nhất quán của kỳ thi.",
    action: "Giữ nguyên câu hỏi trong ngân hàng đề.",
  },
  {
    id: 12,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "up",
    deltaR: "down",
    labelP: "→ Ổn",
    labelD: "↑ Tăng",
    labelR: "↓ Giảm",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Phân loại tốt hơn nhưng các phương án sai có phân bố chưa đồng đều.",
    action: "Tinh chỉnh lại câu chữ các đáp án gây nhiễu.",
  },
  {
    id: 13,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "stable",
    deltaR: "up",
    labelP: "→ Ổn",
    labelD: "→ Ổn",
    labelR: "↑ Tăng",
    assessment: "Ổn định",
    variant: "default",
    explanation: "Câu hỏi đo lường ngày càng chuẩn xác, sai số ngẫu nhiên giảm.",
    action: "Giữ nguyên sử dụng.",
  },
  {
    id: 14,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "stable",
    deltaR: "stable",
    labelP: "→ Ổn",
    labelD: "→ Ổn",
    labelR: "→ Ổn",
    assessment: "Hoàn toàn ổn định",
    variant: "default",
    explanation: "Câu hỏi đạt trạng thái cân bằng tuyệt đối qua nhiều kỳ thi.",
    action: "Chuẩn mực đánh giá định kỳ.",
  },
  {
    id: 15,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "stable",
    deltaR: "down",
    labelP: "→ Ổn",
    labelD: "→ Ổn",
    labelR: "↓ Giảm",
    assessment: "Ổn định",
    variant: "default",
    explanation: "Độ khó và phân loại ổn định nhưng bắt đầu có dao động ngẫu nhiên trong các lựa chọn.",
    action: "Theo dõi thêm ở kỳ thi kế tiếp.",
  },
  {
    id: 16,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "down",
    deltaR: "up",
    labelP: "→ Ổn",
    labelD: "↓ Giảm",
    labelR: "↑ Tăng",
    assessment: "Suy giảm phân loại",
    variant: "destructive",
    explanation: "Độ khó không đổi nhưng khả năng phân biệt giảm (sinh viên giỏi lại chọn nhầm phương án nhiễu).",
    action: "Kiểm tra xem phương án nhiễu có gây hiểu lầm cho học sinh giỏi không.",
  },
  {
    id: 17,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "down",
    deltaR: "stable",
    labelP: "→ Ổn",
    labelD: "↓ Giảm",
    labelR: "→ Ổn",
    assessment: "Suy giảm phân loại",
    variant: "destructive",
    explanation: "Câu hỏi không còn tách biệt được nhóm học sinh xuất sắc và trung bình.",
    action: "Cần điều chỉnh lại stem (đề dẫn) cho rõ ý định khảo thí.",
  },
  {
    id: 18,
    group: "p_stable",
    groupLabel: "Nhóm II: Tỷ lệ làm đúng ổn định (Độ khó giữ nguyên)",
    deltaP: "stable",
    deltaD: "down",
    deltaR: "down",
    labelP: "→ Ổn",
    labelD: "↓ Giảm",
    labelR: "↓ Giảm",
    assessment: "Suy giảm",
    variant: "destructive",
    explanation: "Câu hỏi mất dần giá trị phân loại và độ tin cậy.",
    action: "Cần thiết kế lại các phương án lựa chọn.",
  },

  // Nhóm III: deltaP Giảm (Câu hỏi khó hơn)
  {
    id: 19,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "up",
    deltaR: "up",
    labelP: "↓ Giảm",
    labelD: "↑ Tăng",
    labelR: "↑ Tăng",
    assessment: "Cải thiện độ phân hóa",
    variant: "success",
    explanation: "Câu hỏi được nâng cao độ khó thành công và trở thành câu phân loại sinh viên xuất sắc rất tốt.",
    action: "Rất tốt cho đề thi phân loại cao (chọn học bổng, thi học sinh giỏi).",
  },
  {
    id: 20,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "up",
    deltaR: "stable",
    labelP: "↓ Giảm",
    labelD: "↑ Tăng",
    labelR: "→ Ổn",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Độ khó tăng lên và phân loại sinh viên giỏi rõ rệt hơn.",
    action: "Phù hợp làm câu hỏi vận dụng cao.",
  },
  {
    id: 21,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "up",
    deltaR: "down",
    labelP: "↓ Giảm",
    labelD: "↑ Tăng",
    labelR: "↓ Giảm",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Khó hơn và phân loại được, nhưng một số phương án nhiễu không có ai chọn.",
    action: "Xóa bớt hoặc đổi phương án nhiễu không hiệu quả.",
  },
  {
    id: 22,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "stable",
    deltaR: "up",
    labelP: "↓ Giảm",
    labelD: "→ Ổn",
    labelR: "↑ Tăng",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Tăng độ thử thách một cách chuẩn xác mà không gây méo mó kết quả phân loại.",
    action: "Giữ nguyên câu hỏi.",
  },
  {
    id: 23,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "stable",
    deltaR: "stable",
    labelP: "↓ Giảm",
    labelD: "→ Ổn",
    labelR: "→ Ổn",
    assessment: "Cải thiện",
    variant: "success",
    explanation: "Câu hỏi khó hơn một mức vừa phải, các chỉ số khác không đổi.",
    action: "Phù hợp nếu mục tiêu đề thi là siết chuẩn điểm số.",
  },
  {
    id: 24,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "stable",
    deltaR: "down",
    labelP: "↓ Giảm",
    labelD: "→ Ổn",
    labelR: "↓ Giảm",
    assessment: "Ổn định",
    variant: "default",
    explanation: "Khó hơn nhưng độ tin cậy bắt đầu suy giảm do sinh viên đoán mò nhiều.",
    action: "Cần kiểm tra xem câu hỏi có quá dài dòng hoặc quá phức tạp không.",
  },
  {
    id: 25,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "down",
    deltaR: "up",
    labelP: "↓ Giảm",
    labelD: "↓ Giảm",
    labelR: "↑ Tăng",
    assessment: "Suy giảm",
    variant: "destructive",
    explanation: "Câu hỏi khó hơn nhưng học sinh giỏi lại làm sai, học sinh trung bình làm đúng (nghịch lý bẫy sai).",
    action: "Cảnh báo lỗi bẫy sai kiến thức: Cần xem lại đáp án chính xác.",
  },
  {
    id: 26,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "down",
    deltaR: "stable",
    labelP: "↓ Giảm",
    labelD: "↓ Giảm",
    labelR: "→ Ổn",
    assessment: "Suy giảm",
    variant: "destructive",
    explanation: "Câu hỏi quá hóc búa, sinh viên mất phương hướng khi làm bài.",
    action: "Giảm bớt độ phức tạp, làm rõ câu hỏi.",
  },
  {
    id: 27,
    group: "p_down",
    groupLabel: "Nhóm III: Tỷ lệ làm đúng giảm (Câu hỏi trở nên khó hơn)",
    deltaP: "down",
    deltaD: "down",
    deltaR: "down",
    labelP: "↓ Giảm",
    labelD: "↓ Giảm",
    labelR: "↓ Giảm",
    assessment: "Suy giảm nghiêm trọng",
    variant: "destructive",
    explanation: "Câu hỏi quá đánh đố / sai kiến thức khiến toàn bộ sinh viên đoán mò, phân loại âm.",
    action: "Loại bỏ ngay khỏi ngân hàng đề thi.",
  },
];

export function evaluateMatrixCase(
  firstMetric: { difficulty?: number | null; correctRate?: number | null; discrimination?: number | null; reliability?: number | null } | null | undefined,
  lastMetric: { difficulty?: number | null; correctRate?: number | null; discrimination?: number | null; reliability?: number | null } | null | undefined
): {
  matchedCase: MatrixCase | null;
  deltaP: number;
  deltaD: number;
  deltaR: number;
} {
  if (!firstMetric || !lastMetric) {
    return { matchedCase: null, deltaP: 0, deltaD: 0, deltaR: 0 };
  }

  const pFirst = firstMetric.difficulty ?? firstMetric.correctRate ?? 0;
  const pLast = lastMetric.difficulty ?? lastMetric.correctRate ?? 0;
  const dFirst = firstMetric.discrimination ?? 0;
  const dLast = lastMetric.discrimination ?? 0;
  const rFirst = firstMetric.reliability ?? 0;
  const rLast = lastMetric.reliability ?? 0;

  const deltaP = pLast - pFirst;
  const deltaD = dLast - dFirst;
  const deltaR = rLast - rFirst;

  const getDir = (val: number, threshold = 0.05): Direction => {
    if (val > threshold) return "up";
    if (val < -threshold) return "down";
    return "stable";
  };

  const dirP = getDir(deltaP, 0.05);
  const dirD = getDir(deltaD, 0.05);
  const dirR = getDir(deltaR, 0.05);

  const matched = MATRIX_27_CASES.find(
    (c) => c.deltaP === dirP && c.deltaD === dirD && c.deltaR === dirR
  ) || null;

  return {
    matchedCase: matched,
    deltaP,
    deltaD,
    deltaR,
  };
}
