-- Additive evidence ledger. Existing submissions and snapshots remain untouched.
CREATE TABLE `proctoring_evidence_captures` (
  `id` VARCHAR(191) NOT NULL,
  `submissionId` VARCHAR(191) NOT NULL,
  `examInstanceId` VARCHAR(191) NOT NULL,
  `status` ENUM('REQUESTED', 'UPLOADED', 'ANALYZING', 'ANALYZED', 'FAILED', 'PURGED') NOT NULL DEFAULT 'REQUESTED',
  `trigger` ENUM('IDLE', 'SUSPICIOUS_EVENT') NOT NULL,
  `triggerDetails` JSON NULL,
  `captureNonceHash` VARCHAR(64) NOT NULL,
  `nonceExpiresAt` DATETIME(3) NOT NULL,
  `storageKey` VARCHAR(512) NULL,
  `contentHash` VARCHAR(64) NULL,
  `mimeType` VARCHAR(100) NULL,
  `sizeBytes` INTEGER NULL,
  `aiTags` JSON NULL,
  `aiProvider` VARCHAR(100) NULL,
  `aiAnalyzedAt` DATETIME(3) NULL,
  `aiError` TEXT NULL,
  `reviewStatus` ENUM('PENDING', 'REVIEWED', 'DISMISSED') NOT NULL DEFAULT 'PENDING',
  `reviewedById` VARCHAR(191) NULL,
  `reviewerNote` TEXT NULL,
  `reviewedAt` DATETIME(3) NULL,
  `capturedAt` DATETIME(3) NULL,
  `retentionUntil` DATETIME(3) NOT NULL,
  `purgedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `proctoring_evidence_captures_captureNonceHash_key` (`captureNonceHash`),
  UNIQUE INDEX `proctoring_evidence_captures_storageKey_key` (`storageKey`),
  INDEX `proctoring_evidence_captures_submissionId_createdAt_idx` (`submissionId`, `createdAt`),
  INDEX `proctoring_evidence_captures_examInstanceId_createdAt_idx` (`examInstanceId`, `createdAt`),
  INDEX `proctoring_evidence_captures_status_retentionUntil_idx` (`status`, `retentionUntil`),
  INDEX `proctoring_evidence_captures_reviewedById_idx` (`reviewedById`),
  CONSTRAINT `proctoring_evidence_captures_submissionId_fkey` FOREIGN KEY (`submissionId`) REFERENCES `exam_submissions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `proctoring_evidence_captures_examInstanceId_fkey` FOREIGN KEY (`examInstanceId`) REFERENCES `exam_instances` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `proctoring_evidence_captures_reviewedById_fkey` FOREIGN KEY (`reviewedById`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
